services:

  # mysql
  mysql-9:
    image: "mysql:9.5.0"
    container_name: "typeorm-mysql-9"
    pull_policy: never
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  # mariadb
  mariadb-12:
    image: "mariadb:12.1.2"
    container_name: "typeorm-mariadb-12"
    pull_policy: never
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  # postgres
  postgres-17:
    platform: linux/amd64
    image: "ghcr.io/naorpeled/typeorm-postgres:pg17-postgis3-pgvectorv0.8.0"
    container_name: "typeorm-postgres-17"
    pull_policy: never
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  # mongodb
  mongodb:
    image: "mongo:8"
    container_name: "typeorm-mongodb"
    pull_policy: never
    ports:
      - "27017:27017"
